name: macos

on:
  push:
    branches: [ master, ts ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    env:
      DBFARM: dbfarm

    strategy:
      matrix:
        node: ['20', '22', '23', '24']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - name: Install MonetDB
      run: |
          brew install monetdb
    - name: create database
      run: |
          monetdbd create ${{ env.DBFARM }}
          monetdbd start ${{ env.DBFARM }}
          monetdb create test
          monetdb release test
          monetdb start test
    - name: Run Unit-Tests
      run: |
            npm t
